# Generated by Django 4.2.7 on 2023-11-29 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_option_question_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='response',
            field=models.ForeignKey(limit_choices_to={'question': models.F('question')}, on_delete=django.db.models.deletion.CASCADE, to='quiz.option'),
        ),
    ]
